# Supabase Configuration for CutMatch

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://cutmatch.app", "exp://"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
image_transformation = true
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54325

[analytics]
enabled = false

[inbound_webhooks]
enabled = false

[functions.cutmatch-api]
verify_jwt = false

